CREATE TABLE IF NOT EXISTS shippings (
  uid uuid PRIMARY KEY,
  address VARCHAR NOT NULL DEFAULT '',
  city VARCHAR NOT NULL DEFAULT '',
  postal_code INTEGER NOT NULL,
  country VARCHAR NOT NULL DEFAULT ''
);
