steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
              'build',
              '-t', 'gcr.io/p06111806/frontend:latest',
              '--cache-from', 'gcr.io/p06111806/frontend:latest',
              '.'
          ]
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/p06111806/frontend:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'frontend'
    - '--image'
    - 'gcr.io/p06111806/frontend:latest'
    - '--region'
    - 'asia-northeast1'
images:
  - 'gcr.io/p06111806/frontend:latest'
