steps:
  # [START cloudbuild_go_image_yaml]
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t','gcr.io/p06111806/frontend:$SHORT_SHA', '.']
  # [END cloudbuild_go_image_yaml]

  # [START cloudbuild_go_push_yaml]
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/p06111806/frontend :$SHORT_SHA:$SHORT_SHA']
  # [END cloudbuild_go_push_yaml]

  # [START cloudbuild_go_deploy_yaml]
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'frontend-${SHORT_SHA}','--image=gcr.io/p06111806/frontend :$SHORT_SHA:$SHORT_SHA','--region', 'asia-northeast1', '--platform', 'managed']
  # [END cloudbuild_go_deploy_yaml]

# [START cloudbuild_go_logs_yaml]
# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://$_BUCKET_NAME/
    paths:
      - ${SHORT_SHA}_test_log.xml
# [END cloudbuild_go_logs_yaml]
# Store images in Google Artifact Registry
images:
  - gcr.io/p06111806/frontend :$SHORT_SHA:$SHORT_SHA
# [END cloudbuild_go_yaml]
