version: "3.8"
services:
  postgres-backend:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    #   Set a volume for data and initial sql script
    #   May configure initial db for future demo
    volumes:
      - "pgdata_backend:/var/lib/postgresql/data"
      # - ./init:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "log_statement=all"]
  redis-backend:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  backend:
    build:
      context: ./backend
      target: builder
    image: backend
    env_file: ./backend/.env.dev
    expose:
      - "8080"
    environment:
      - ENV=dev
    volumes:
      - ./backend:/go/src/app
    depends_on:
      - postgres-backend
      - redis-backend
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
  pgadmin:
      image: dpage/pgadmin4
      environment:
          - PGADMIN_DEFAULT_EMAIL=root@root.com
          - PGADMIN_DEFAULT_PASSWORD=root
      ports:
          - '5050:80'
      restart: always
volumes:
  pgdata_backend:
  redisdata:

