import Head from 'next/head'
import Image from 'next/image'
import useSWR from 'swr'
import { Game } from '../components/Game'
import styles from '../styles/Home.module.css'
const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL
const fetcher = (url:string) => fetch(url).then(r => r.json())

const Home: React.FC = () => {
  console.log(`${BASE_URL}/api`)
  const { data, error } = useSWR(`${BASE_URL}/api`, fetcher)
  console.log("data",data)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>
  return <div>aaa</div>
  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <Game />
  //     </main>

  //   </div>
  // )
}

// eslint-disable-next-line import/no-default-export
export default Home
